import { useEffect, useState } from "react";
import { getStatus, listSamples, analyzeFile, analyzeSample } from "./api";
import UploadPanel from "./components/UploadPanel.jsx";
import HealthScoreHero from "./components/HealthScoreHero.jsx";
import AlertBanner from "./components/AlertBanner.jsx";
import ParameterTable from "./components/ParameterTable.jsx";
import InsightsPanel from "./components/InsightsPanel.jsx";
import RecommendationsPanel from "./components/RecommendationsPanel.jsx";
import ExplanationsPanel from "./components/ExplanationsPanel.jsx";

export default function App() {
  const [status, setStatus] = useState(null);
  const [samples, setSamples] = useState([]);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [view, setView] = useState("upload");

  useEffect(() => {
    getStatus().then(setStatus).catch(() => setStatus(null));
    listSamples().then(setSamples).catch(() => setSamples([]));
  }, []);

  const runAnalysis = async (promise) => {
    setLoading(true);
    setError(null);
    try {
      const data = await promise;
      if (data.success) {
        setReport(data.report);
        setView("report");
      } else {
        setError((data.errors && data.errors.join(" ")) || "Analysis failed.");
      }
    } catch (e) {
      setError("Could not reach the backend. Is the FastAPI server running on :8000?");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="shell">
      <aside className="rail">
        <p className="brand">Vitals</p>
        <p className="brand-sub">AI Health Report Analyzer &amp; Personal Health Assistant</p>

        <p className="rail-section-label">Navigate</p>
        <div className="rail-nav">
          <button className={view === "upload" ? "active" : ""} onClick={() => setView("upload")}>
            Upload report
          </button>
          <button
            className={view === "report" ? "active" : ""}
            onClick={() => report && setView("report")}
            disabled={!report}
          >
            Report {report ? "" : "(none yet)"}
          </button>
        </div>

        <div className="rail-status">
          <div>
            <span className={`status-dot ${status ? "" : "off"}`} />
            {status ? "Backend connected" : "Backend offline"}
          </div>
          {status && (
            <>
              <div>Engine: {status.pipeline_engine}</div>
              <div>LLM: {status.llm_enabled ? "Claude API" : "rule-based fallback"}</div>
            </>
          )}
        </div>
      </aside>

      <main className="main">
        {view === "upload" && (
          <>
            <p className="eyebrow-row" />
            <h1 className="page-title">Understand your blood report</h1>
            <p className="page-lede">
              Upload a lab report and a four-agent pipeline extracts every parameter, compares it
              against WHO / NIH / Mayo Clinic reference ranges, and turns it into a plain-language
              health summary with personalized recommendations.
            </p>
            <UploadPanel
              onFile={(file) => runAnalysis(analyzeFile(file))}
              samples={samples}
              onSample={(name) => runAnalysis(analyzeSample(name))}
              loading={loading}
            />
            {loading && (
              <div className="empty-state">
                <div className="spinner" />
                Running the report through the four agents…
              </div>
            )}
            {error && <div className="error-box" style={{ marginTop: 20 }}>{error}</div>}
          </>
        )}

        {view === "report" && report && (
          <>
            <h1 className="page-title">Health summary</h1>
            <AlertBanner report={report} />
            <HealthScoreHero report={report} />
            <hr className="hr" />
            <ParameterTable parameters={report.parameters} />
            <hr className="hr" />
            <InsightsPanel report={report} />
            <hr className="hr" />
            <RecommendationsPanel recs={report.recommendations} />
            <hr className="hr" />
            <ExplanationsPanel explanations={report.parameter_explanations} />
            <p className="disclaimer">
              This report is generated by an AI system for informational purposes only. It is not a
              medical diagnosis and does not replace advice from a qualified healthcare
              professional. Always consult your doctor about any abnormal results.
            </p>
          </>
        )}
      </main>
    </div>
  );
}
