"""
Agent 2 -- Medical Analysis Agent

Responsibilities:
  - Retrieve medical knowledge (RAG over the curated WHO / NIH / Mayo
    Clinic reference table -- see app.reference_ranges)
  - Compare blood values with reference ranges
  - Detect nutritional deficiencies
  - Identify abnormal parameters
  - Analyze possible health risks
  - Explain every blood parameter in simple language

If ANTHROPIC_API_KEY is configured, explanations/risk reasoning are
generated by Claude, grounded with the retrieved reference-range
context (a lightweight RAG pattern). Otherwise a deterministic
rule-based engine produces the same fields.
"""
from app.models import PipelineState, MedicalAnalysis, DeficiencyOrRisk
from app.reference_ranges import get_reference, normalize_parameter_name
from app.llm_client import claude_client

DEFICIENCY_PARAMS = {"hemoglobin", "vitamin d", "vitamin b12", "serum iron", "ferritin", "calcium"}

SIMPLE_EXPLANATIONS = {
    "hemoglobin": "Carries oxygen in your blood. Low levels can mean anemia and cause fatigue.",
    "hematocrit": "The percentage of your blood made up of red blood cells.",
    "wbc count": "White blood cells fight infection; high counts can signal infection or inflammation.",
    "rbc count": "Red blood cells carry oxygen from your lungs to the rest of your body.",
    "platelet count": "Platelets help your blood clot; very low or high counts need medical attention.",
    "fasting blood glucose": "Blood sugar after fasting; consistently high levels can indicate prediabetes/diabetes.",
    "hba1c": "Reflects your average blood sugar over the last ~3 months.",
    "total cholesterol": "A measure of fats in your blood linked to heart disease risk.",
    "ldl cholesterol": "'Bad' cholesterol — high levels raise heart disease risk.",
    "hdl cholesterol": "'Good' cholesterol — higher levels help protect your heart.",
    "triglycerides": "A type of fat in blood; high levels are linked to heart disease.",
    "tsh": "Signals your thyroid to produce hormones; abnormal levels affect metabolism.",
    "vitamin d": "Supports bone health and immunity; low levels are very common.",
    "vitamin b12": "Needed for nerve function and red blood cell production.",
    "serum creatinine": "A waste product filtered by kidneys; high levels can signal reduced kidney function.",
    "urea": "A waste product related to kidney function.",
    "sgpt": "A liver enzyme; elevated levels can indicate liver stress or damage.",
    "sgot": "A liver/muscle enzyme; elevated levels can indicate liver stress or damage.",
    "serum iron": "The amount of iron circulating in your blood.",
    "ferritin": "Reflects your body's stored iron levels.",
    "calcium": "Important for bones, muscles, and nerve function.",
    "sodium": "An electrolyte that balances fluids in your body.",
    "potassium": "An electrolyte critical for heart and muscle function.",
}


def _rule_based_analysis(state: PipelineState) -> MedicalAnalysis:
    explanations = {}
    deficiencies = []
    risks = []
    abnormal = []

    for param in state.extracted.parameters:
        canonical = normalize_parameter_name(param.name) or param.name.lower()
        explanations[param.name] = SIMPLE_EXPLANATIONS.get(
            canonical, "A standard blood test parameter compared against a healthy reference range."
        )

        if param.status in ("low", "critical_low", "high", "critical_high"):
            abnormal.append(param.name)
            severity = "severe" if "critical" in param.status else "moderate"

            if param.status in ("low", "critical_low") and canonical in DEFICIENCY_PARAMS:
                deficiencies.append(DeficiencyOrRisk(
                    title=f"Low {param.name}",
                    parameter=param.name,
                    severity=severity,
                    explanation=(f"Your {param.name} ({param.value} {param.unit or ''}) is below the "
                                 f"healthy reference range, which may indicate a deficiency. "
                                 f"{SIMPLE_EXPLANATIONS.get(canonical, '')}"),
                ))
            else:
                direction = "below" if "low" in param.status else "above"
                risks.append(DeficiencyOrRisk(
                    title=f"{param.name} out of range",
                    parameter=param.name,
                    severity=severity,
                    explanation=(f"Your {param.name} ({param.value} {param.unit or ''}) is {direction} "
                                 f"the healthy reference range. {SIMPLE_EXPLANATIONS.get(canonical, '')}"),
                ))

    return MedicalAnalysis(
        parameter_explanations=explanations,
        deficiencies=deficiencies,
        health_risks=risks,
        abnormal_parameters=abnormal,
        sources_consulted=sorted({
            get_reference(normalize_parameter_name(p.name))["source"]
            for p in state.extracted.parameters
            if normalize_parameter_name(p.name) and get_reference(normalize_parameter_name(p.name))
        }),
    )


def _build_llm_context(state: PipelineState) -> str:
    lines = []
    for p in state.extracted.parameters:
        canonical = normalize_parameter_name(p.name)
        ref = get_reference(canonical) if canonical else None
        ref_str = f"{ref['low']}-{ref['high']} {ref['unit']} (source: {ref['source']})" if ref else "no reference on file"
        lines.append(f"- {p.name}: {p.value} {p.unit or ''} | status={p.status} | reference={ref_str}")
    return "\n".join(lines)


def run(state: PipelineState) -> PipelineState:
    if not state.extracted or not state.extracted.parameters:
        state.analysis = MedicalAnalysis()
        return state

    if claude_client.available:
        context = _build_llm_context(state)
        patient_note = ""
        if state.patient_info:
            patient_note = f"Patient context: {state.patient_info.model_dump()}"
        system = (
            "You are a careful medical-information assistant grounded strictly in the "
            "reference-range data provided. Never invent lab values. Explain in simple, "
            "friendly language a non-medical person can understand. Return ONLY valid JSON "
            "matching this schema: {\"parameter_explanations\": {name: string}, "
            "\"deficiencies\": [{\"title\":str,\"parameter\":str,\"severity\":str,\"explanation\":str}], "
            "\"health_risks\": [{\"title\":str,\"parameter\":str,\"severity\":str,\"explanation\":str}], "
            "\"abnormal_parameters\": [str]}"
        )
        user = f"Blood parameters with status:\n{context}\n\n{patient_note}"
        result = claude_client.complete_json(system, user)
        if result:
            try:
                analysis = MedicalAnalysis(
                    parameter_explanations=result.get("parameter_explanations", {}),
                    deficiencies=[DeficiencyOrRisk(**d) for d in result.get("deficiencies", [])],
                    health_risks=[DeficiencyOrRisk(**r) for r in result.get("health_risks", [])],
                    abnormal_parameters=result.get("abnormal_parameters", []),
                    sources_consulted=["WHO", "NIH", "Mayo Clinic (via curated reference set)"],
                )
                state.analysis = analysis
                return state
            except Exception:  # noqa: BLE001
                pass  # fall through to rule-based

    state.analysis = _rule_based_analysis(state)
    return state
